### ISSUE TITLE
curriculum: ensure smart/scalable nh2020-curriculum access

### ISSUE THREAD

**Issue by consideRatio** [neurohackademy/nh2020-jupyterhub#26]
We want to provide access to the [neurohackademy/nh2020-curriculum](https://github.com/neurohackademy/nh2020-curriculum) repo's content one way or another, but there are some considerations.

1. Avoid needing to restart the hub to update the repo content.
1. Avoid relying on GitHub access for two reasons:
   1. Too many GitHub pull commands in a short time from a small set of IPs could get throttled and fail.
   1. GitHub may be down.
1. Ensure access to the repo content behaves sensible:
   1. Local read/write access for the user on a copy
   1. Whatever the user change should remain locally on user pod restarts
   1. Whatever the curriculum author change remotely should update through a git merge giving priority to the local changes on user pod restarts.

### /nh/curriculum on the NFS storage
To avoid relying too much on GitHub access, I'll ensure that the NFS storage at /nh/curriculum is updated using a git-sync solution that updates every minute or so. Doing this means adding of a single k8s pod (Deployment: 1 replica) in the Helm chart we have, which mounts the NFS storage in read/write mode and writes to it when needed.

### /home/jovyan/curriculum on the users local storage
/home/jovyan/curriculum should be made to contain a read/write only version of the repo that automatically [`gitpuller`](https://github.com/jupyterhub/nbgitpuller) syncs on user pod startup. I plan to let this run as a small script that is mounted from the Helm chart to the user pods, which makes it easy to update etc without rebuilding the image etc.

We can use a k8s lifecyleHook to ensure the scripts run on pod startup.

## Tasks
- [x] Implement some git sync solution of neurohackademy/nh2020-curriculum to NFS /nh/curriculum
  **NOTE:** I tried using [kubernetes/git-sync](https://github.com/kubernetes/git-sync) but concluded it was the wrong way to go because of its use of symlinks switching from one destination to another back and forth while updating. This would become a bit messy if we would use our NFS mount to write to a single folder. Due to this, I instead used a very basic git-clone or git-pull script started as a CronJob in an apline/git docker image.
- [x] Implement gitpuller script on pod startup using a lifecycleHook running the ConfigMap mounted script
- [x] Document whats needed in the jupyter-book for participants and instructors
  **NOTE:** Documentation provided in https://neurohackademy.github.io/nh2020-jupyterhub/instructor/storage.html#notebooks-for-tutorials

**Comment by arokem** [comment]
This sounds like a great solution!
